data:
  datasetname: ogbg-molhiv
  datasize: 99999
  batch_size: 64

model:
  hidden_channels: 128
  out_channels: 1
  p: 0.5
  num_layers: 3

optimizer:
  lr: 0.0005
  weight_decay: 0.005

training:
  epochs: 50
  max_grad_norm: 1

reduce_on_plateau_scheduler:
  mode: min
  factor: 0.5
  patience: 5
  min_lr: 1.0e-6

cosine_annealing_scheduler:
  T_max: 50
  eta_min: 1.0e-6

loss:
  type: BCEWithLogitsLoss