data:
  datasetname: ogbg-molhiv
  datasize: 99999
  batch_size: 64

model:
  hidden_channels: 256
  out_channels: 1
  p: 0.1
  num_layers: 6

optimizer:
  lr: 0.001
  weight_decay: 0.001

training:
  epochs: 50
  max_grad_norm: 1

scheduler:
  mode: min
  factor: 0.5
  patience: 5
  min_lr: 1.0e-6

loss:
  type: BCEWithLogitsLoss